import type { Metadata } from "next";
import "./globals.css";
import { Raleway } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import { SidebarProvider } from "@/providers/sidebar-provider";
import ReduxProvider from "@/providers/redux-provider";

const raleway = Raleway({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-raleway",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
interface IProp {
  children: React.ReactNode;
}
export default function RootLayout({ children }: IProp) {
  return (
    <html lang="en" className={`${raleway.variable}`}>
      <body suppressHydrationWarning={true}>
        <ReduxProvider>
          <SidebarProvider>
            <NextTopLoader
              color="#e3ff00"
              initialPosition={0.08}
              crawlSpeed={200}
              height={3}
              crawl={true}
              showSpinner={false}
              easing="ease"
              speed={200}
              shadow="0 0 10px #2299DD,0 0 5px #2299DD"
            />
            {children}
          </SidebarProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
